---
local_users:
  ansible:
    privilege: 15
    role: network-admin
    sha512_password: "$6$Dzu11L7yp9j3nCM9$FSptxMPyIL555OMO.ldnjDXgwZmrfMYwHSr0uznE5Qoqvd9a6UdjiFcJUhGLtvXVZR1r.A/iF5aAt50hf/EK4/"

# Cloud Vision server information
cvp_instance_ip: 192.168.0.5
cvp_ingestauth_key: 'atd-lab'

# OOB Management network default gateway.
mgmt_gateway: 10.255.0.1

# dns servers.
name_servers:
  - 192.168.2.1
  - 8.8.8.8

# NTP Servers IP or DNS name, first NTP server will be prefered, and sourced from Managment VRF
ntp_servers:
  - 0.fr.pool.ntp.org
  - 1.fr.pool.ntp.org