---
# L3LS Fabric Values - update these values with caution,
# SOME CHANGES COULD BE DISRUPTIVE.

fabric_name: ATD_FABRIC

# Point to Point Network Summary range, assigned as /31 for each
# uplink interfaces
# Assign range larger then total [Spines * total potential leafs * 2]
underlay_p2p_network_summary: 172.30.255.0/24

# IP address range for evpn loopback for all switches in fabric,
# assigned as /32s
# Assign range larger then total Spines + total leafs switches
overlay_loopback_network_summary: 192.0.255.0/24

# VTEP VXLAN Tunnel source loopback IP for leaf switches, assigned in /32s
# Assign range larger then total leaf switches
vtep_loopback_network_summary: 192.0.254.0/24

# mlag pair IP assignment - assign blocks - Assign range larger then
# total Spines + total leafs switches
mlag_ips:
  leaf_peer_l3: 10.255.251.0/24
  mlag_peer: 10.255.252.0/24

# Enable vlan aware bundles
vxlan_vlan_aware_bundles: true

# bgp peer groups passwords
bgp_peer_groups:
  IPv4_UNDERLAY_PEERS:
    password: "AQQvKeimxJu+uGQ/yYvv9w=="
  EVPN_OVERLAY_PEERS:
    password: "q+VNViP5i4rVjW1cxFv2wA=="
  MLAG_IPv4_UNDERLAY_PEER:
    password: "vnEaG8gMeQf3d3cN6PktXQ=="

# Spine Switches
spine:
  platform: vEOS-LAB
  bgp_as: 65001
  # defines the range of acceptable remote ASNs from leaf switches
  leaf_as_range: 65101-65132
  nodes:
    spine1:
      id: 1
      mgmt_ip: 192.168.0.10/24
    spine2:
      id: 2
      mgmt_ip: 192.168.0.11/24

# Leaf switch groups
# A maximum of two nodes can form a leaf group
# When two nodes are in a leaf group this will automatically form mlag pair

l3leaf:
  defaults:
    # virtual router mac for VNIs assigned to Leaf switches
    # format: xx:xx:xx:xx:xx:xx
    virtual_router_mac_address: 00:1c:73:00:dc:01
    platform: vEOS-LAB
    bgp_as: 65100
    spines: [spine1, spine2]
    uplink_to_spine_interfaces: [Ethernet2, Ethernet3]
    mlag_interfaces: [Ethernet1]
    spanning_tree_priority: 4096
    spanning_tree_mode: mstp
  node_groups:
    pod1:
      bgp_as: 65101
      nodes:
        leaf1:
          id: 1
          mgmt_ip: 192.168.0.12/24
          spine_interfaces: [Ethernet2, Ethernet2]
        leaf2:
          id: 2
          mgmt_ip: 192.168.0.13/24
          spine_interfaces: [Ethernet3, Ethernet3]
    pod2:
      bgp_as: 65102
      nodes:
        leaf3:
          id: 3
          mgmt_ip: 192.168.0.14/24
          spine_interfaces: [Ethernet4, Ethernet4]
        leaf4:
          id: 4
          mgmt_ip: 192.168.0.15/24
          spine_interfaces: [Ethernet5, Ethernet5]

#### Override for vEOS Lab Caveats ####

# Disable update wait-for-convergence and update wait-for-install,
# which is not supported in vEOS-LAB.
# Refer to design guide

spine_bgp_defaults:
  #  - update wait-for-convergence
  #  - update wait-install
  - no bgp default ipv4-unicast
  - distance bgp 20 200 200
  - graceful-restart restart-time 300
  - graceful-restart

leaf_bgp_defaults:
  #  - update wait-install
  - no bgp default ipv4-unicast
  - distance bgp 20 200 200
  - graceful-restart restart-time 300
  - graceful-restart

# Update p2p mtu 9000 -> 1500
p2p_uplinks_mtu: 1500

# Adjust default bfd values
bfd_multihop:
  interval: 1200
  min_rx: 1200
  multiplier: 3

# List of additional CVP configlets to bind to devices and containers
# Configlets MUST be configured on CVP before running AVD playbooks.

# cv_configlets:
#   containers:
#     DC1_L3LEAFS:
#       - ASE_GLOBAL-ALIASES

ansible_connection: httpapi
ansible_network_os: eos
ansible_become: true
ansible_become_method: enable
ansible_httpapi_use_ssl: true
ansible_httpapi_validate_certs: false