---
port_profiles:
  TENANT_A:
    mode: access
    vlans: "110"


servers:
  host1:
    rack: pod1
    adapters:
      - type: nic
        server_ports: [Eth1, Eth2, Eth3, Eth4]
        switch_ports: [Ethernet4, Ethernet5, Ethernet4, Ethernet5]
        switches: [leaf1,leaf1, leaf2, leaf2]
        profile: TENANT_A
        port_channel:
          state: present
          description: PortChannel
          mode: active

  host2:
    rack: pod2
    adapters:
      - type: nic
        server_ports: [Eth1, Eth2, Eth3, Eth4]
        switch_ports: [Ethernet4, Ethernet5, Ethernet4, Ethernet5]
        switches: [leaf3, leaf3, leaf4, leaf4]
        profile: TENANT_A
        port_channel:
          state: present
          description: PortChannel
          mode: active

# Sample network port config as access ports
# For multiport port-channel setup, please use the connected endpoint example above

# network_ports:
#   - switches:
#       - leaf[34] # Simple regex to match on leaf3 and leaf4
#     switch_ports: # Ex Ethernet1-48 or Ethernet2-3/1-48
#       - Ethernet4-5
#     description: Connection to host2
#     profile: TENANT_A
