---
# tasks file for atd-provisioner
# tasks file for eos-config-deploy-cvp - state=present
- name: "Building Containers topology on {{ inventory_hostname }}"
  tags: [provision, apply]
  arista.cvp.cv_container_v3:
    topology: '{{ CVP_CONTAINERS_INIT }}'

- name: "Configure devices on {{ inventory_hostname }}"
  tags: [provision, apply]
  arista.cvp.cv_device_v3:
    devices: "{{ CVP_DEVICES_INIT }}"
    state: present
  register: cvp_device_results

- name: "Execute pending tasks on {{ inventory_hostname }}"
  tags: [apply]
  arista.cvp.cv_task_v3:
    tasks: "{{ cvp_device_results.taskIds }}"
  when:
    - execute_tasks|bool
    - cvp_device_results.taskIds | length > 0

- name: "Refresh Containers topology on {{ inventory_hostname }}"
  tags: [provision, apply]
  arista.cvp.cv_container_v3:
    topology: '{{ CVP_CONTAINERS_DELETE }}'
    state: absent
