---
- name: Manage Arista EOS EVPN/VXLAN Configuration
  hosts: ATD_FABRIC
  connection: local
  gather_facts: false
  collections:
    - arista.avd
  vars:
    fabric_dir_name: "{{fabric_name}}"
    execute_tasks: false
  tasks:

    - name: Generate intended variables
      # Available tags are: build / debug
      import_role:
        name: eos_designs

    - name: Generate device intended config and documentation
      tags: [build, generate]
      import_role:
        name: eos_cli_config_gen

- name: Configuration deployment with CVP
  hosts: cv_servers
  connection: local
  gather_facts: false
  collections:
    - arista.avd
  tasks:
    - name: Provision CVP with AVD configuration
      import_role:
        name: eos_config_deploy_cvp
      vars:
        container_root: 'ATD_FABRIC'
        configlets_prefix: 'AVD'
        # device_filter: 'DC1'
        state: present
